<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Module.CommonDbService\Module.CommonDbService.csproj" />
    <ProjectReference Include="..\..\WSIMS-ERP.Shared\WSIMS-ERP.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\SignIn\" />
  </ItemGroup>

</Project>
